SNAPLEN = 65536  # Maximum number of bytes to capture per packet
PROMISCOUS_MODE = 1  # value 1 implies true
CAPTURE_TIMEOUT = 100000  # In milliseconds
ETH_LENGTH = 14
ICMPH_LENGTH = 4
IP_PROTOCOL = 8
TCP_PROTOCOL = 6
ICMP_PROTOCOL = 1
UDP_PROTOCOL = 17
UDPH_LENGTH = 8