# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srcIP', models.CharField(max_length=16)),
                ('desIP', models.CharField(max_length=16)),
                ('breach_confidence', models.IntegerField()),
                ('remark', models.CharField(max_length=250)),
            ],
        ),
    ]
