# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 19:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catg', models.CharField(max_length=25)),
                ('geolat', models.FloatField()),
                ('geolon', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='packet',
            name='remark',
        ),
        migrations.AddField(
            model_name='packet',
            name='Com_MAC',
            field=models.CharField(default='0.0.0.0S', max_length=19),
        ),
        migrations.AddField(
            model_name='packet',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='packet',
            name='desIP',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='packet',
            name='srcIP',
            field=models.CharField(max_length=25),
        ),
        migrations.AddField(
            model_name='ct',
            name='pac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bds.Packet'),
        ),
    ]
