# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bds', '0002_auto_20170401_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='traff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(default=b'April', max_length=25)),
                ('traffic', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='packet',
            name='Com_MAC',
            field=models.CharField(default='0.0.0.0', max_length=19),
        ),
    ]
