# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 03:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bds', '0003_auto_20170401_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packet',
            old_name='desIP',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='packet',
            old_name='Com_MAC',
            new_name='mac',
        ),
        migrations.RenameField(
            model_name='packet',
            old_name='srcIP',
            new_name='source',
        ),
    ]
