# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bds', '0003_auto_20170401_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ct',
            name='catg',
        ),
        migrations.RemoveField(
            model_name='ct',
            name='geolat',
        ),
        migrations.RemoveField(
            model_name='ct',
            name='geolon',
        ),
        migrations.RemoveField(
            model_name='ct',
            name='pac',
        ),
        migrations.AddField(
            model_name='ct',
            name='breach_confidence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ct',
            name='cod',
            field=models.CharField(default='IN', max_length=3),
        ),
        migrations.AddField(
            model_name='ct',
            name='desIP',
            field=models.CharField(default='0.0.0.0', max_length=25),
        ),
        migrations.AddField(
            model_name='ct',
            name='srcIP',
            field=models.CharField(default='0.0.0.0', max_length=25),
        ),
    ]
