# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bds', '0004_auto_20170402_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='dst_port',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packet',
            name='src_port',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packet',
            name='ttl',
            field=models.IntegerField(default=53),
            preserve_default=False,
        ),
    ]
