# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bds', '0005_auto_20170402_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packet',
            name='breach_confidence',
        ),
    ]
