# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bds', '0006_remove_packet_breach_confidence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packet',
            old_name='mac',
            new_name='dst_mac',
        ),
        migrations.AddField(
            model_name='packet',
            name='src_mac',
            field=models.CharField(default='0.0.0.0', max_length=19),
        ),
    ]
